---
# current program versions as of September 2025
channels:
    - conda-forge
    - bioconda
    - nodefaults

channel_priority: strict

dependencies:
    - pigz=2.8 # parallel handling of gzip files
